server:
  port: 8888

spring:
  zipkin:
    service:
      name: config-server-git
    base-url: ${ZIPKIN_URL}
    enabled: true
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/emreustunn/config-server-repo.git"
          default-label: main #hangi branchten alacağı
          skip-ssl-validation: true
          username: emreustunn
          password: ${GIT_JAVA6_KEY}